version: '3.9'

services:
  postgres:
    image: postgres
    container_name: notify
    environment:
      POSTGRES_DB: ${SQL_DATABASE:-notifications}
      POSTGRES_USER: ${SQL_USER:-postgres}
      POSTGRES_PASSWORD: ${SQL_PASSWORD:-postgres}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${SQL_USER:-postgres} -d ${SQL_DATABASE:-notifications}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - notify_network

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: notification-api
    ports:
      - "8000:8000"
    environment:
      - SQL_USER=${SQL_USER:-postgres}
      - SQL_PASSWORD=${SQL_PASSWORD:-postgres}
      - SQL_DATABASE=${SQL_DATABASE:-notifications}
      - SQL_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - notify_network

networks:
  notify_network:
    driver: bridge

volumes:
  postgres_data:
